routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/historias', 'HistoriaController',['except'=>['destroy','show']]);
Route::resource('/administradores', 'AdministradorController',['except'=>['destroy','show','create','edit','store']]);
Route::resource('/imagen_historia', 'Imagen_HistoriaController');
Route::resource('/noticias', 'NoticaController');
Route::resource('/imagen_noticias', 'Imagen_NoticiasController');
Route::resource('/eventos', 'EventoController');
Route::resource('/imagen_eventos', 'Imagen_EventosController');
Route::resource('/contactos', 'ContactoController');
Route::resource('user', 'UserController');

app/Contacto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contacto extends Model
{
    //
    protected $fillable = [
        'nombre','correo','asunto','descripcion'
    ];
}

app/Http/Controllers/ContactoController.php
<?php

namespace App\Http\Controllers;

use App\Contacto;
use Illuminate\Http\Request;

class ContactoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('contactos.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'nombre'=>'required',
            'correo'=>'required',
            'asunto'=>'required',
            'descripcion'=>'required'
        ]);
        $contatos=Contacto::create($request->except('_token'));
        $contatos->save();

        return redirect('/contactos');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/contactos/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
    <div class="container">
        <form action="{{ route('contactos.store') }}" method="post">
            @csrf
            <div class="input-group">
                <label for="nombre">Nombre :
                    <input type="text" name="nombre" id="nombre" class="form-control" placeholder="nombre">
                </label>
            </div>
            <div class="input-group">
                <label for="correo">Correo :
                    <input type="email" name="correo" id="correo" class="form-control" placeholder="correo">
                </label>
            </div>
            <div class="input-group">
                <label for="asunto">Asunto :
                    <input type="text" name="asunto" id="asunto" class="form-control" placeholder="asunto">
                </label>
            </div>
            <div class="form-group">
              <label for="descripcion">Descripcion :</label>
              <textarea class="form-control" name="descripcion" id="descripcion" rows="9"></textarea>
            </div>
            <button type="submit" class="btn btn-info">Enviar</button>
        </form>
    </div>
</div>
@endsection